language: node_js
node_js:
    "6"

cache:
    directories:
        - $HOME/.npm
        - /tmp/phantomjs

branches:
    only:
        - master

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

